
package services;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Services", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Services {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "TotalRecovered")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TotalRecovered", targetNamespace = "http://services/", className = "services.TotalRecovered")
    @ResponseWrapper(localName = "TotalRecoveredResponse", targetNamespace = "http://services/", className = "services.TotalRecoveredResponse")
    @Action(input = "http://services/Services/TotalRecoveredRequest", output = "http://services/Services/TotalRecoveredResponse")
    public int totalRecovered();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "TotalConfirmed")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TotalConfirmed", targetNamespace = "http://services/", className = "services.TotalConfirmed")
    @ResponseWrapper(localName = "TotalConfirmedResponse", targetNamespace = "http://services/", className = "services.TotalConfirmedResponse")
    @Action(input = "http://services/Services/TotalConfirmedRequest", output = "http://services/Services/TotalConfirmedResponse")
    public int totalConfirmed();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "NewRecovered")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "NewRecovered", targetNamespace = "http://services/", className = "services.NewRecovered")
    @ResponseWrapper(localName = "NewRecoveredResponse", targetNamespace = "http://services/", className = "services.NewRecoveredResponse")
    @Action(input = "http://services/Services/NewRecoveredRequest", output = "http://services/Services/NewRecoveredResponse")
    public int newRecovered();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "NewConfirmed")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "NewConfirmed", targetNamespace = "http://services/", className = "services.NewConfirmed")
    @ResponseWrapper(localName = "NewConfirmedResponse", targetNamespace = "http://services/", className = "services.NewConfirmedResponse")
    @Action(input = "http://services/Services/NewConfirmedRequest", output = "http://services/Services/NewConfirmedResponse")
    public int newConfirmed();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "TotalDeaths")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TotalDeaths", targetNamespace = "http://services/", className = "services.TotalDeaths")
    @ResponseWrapper(localName = "TotalDeathsResponse", targetNamespace = "http://services/", className = "services.TotalDeathsResponse")
    @Action(input = "http://services/Services/TotalDeathsRequest", output = "http://services/Services/TotalDeathsResponse")
    public int totalDeaths();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "NewDeaths")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "NewDeaths", targetNamespace = "http://services/", className = "services.NewDeaths")
    @ResponseWrapper(localName = "NewDeathsResponse", targetNamespace = "http://services/", className = "services.NewDeathsResponse")
    @Action(input = "http://services/Services/NewDeathsRequest", output = "http://services/Services/NewDeathsResponse")
    public int newDeaths();

}
